spring.application.name=auth-service

spring.datasource.url=jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8085

# auth-service application.properties
jwt.secret=b7Kp9mR2xL4nW8vJ3hF6tY1sA5dG0qZwX
jwt.expiration=3600000

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://admin:admin123@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true